### ISSUE TITLE
Arduino IDE 2.0 problem with ESP32-CAM-MB and Module CH340G

### ISSUE THREAD

**Issue by Erhie** [arduino/serial-monitor#17] opened 2022-05-20 13:42 UTC
### Describe the problem

No output in Serial Monitor using Arduino IDE 2.0 RC6 on Windows 10 with ESP32-CAM and CH340G

Because there are some pictures the detailed description in a Google Docs:
[[Arduino IDE 2.0 problem with Serial monitor - Google Docs 2](https://docs.google.com/document/d/1FJyWESVSjLppzBogbrk-TW-JYlIiuwGW_TK8T9bFHm0/edit?usp=sharing)]

[Discussion](https://forum.arduino.cc/t/ide-2-0-not-detecting-board-on-port-but-old-ide-and-vs-code-have-no-issues/703556/24?u=erhy) with **ptillisch** and also tests with CLI nightly build https://downloads.arduino.cc/arduino-cli/nightly/arduino-cli_nightly-latest_Windows_64bit.zip don't solve the problem.

### To reproduce

Plug USB and according the sketch the LED blinks
starting the command `./arduino-cli.exe monitor -p COM5`
The led is dark and the message is
Connected to COM5! Press CTRL-C to exit
no output is logged.

starting the command with unplugged USB
and plug USB few seconds after the message is
```
Connected to COM5! Press CTRL-C to exit.
��f������`���
```
and the led is dark.

With same sketch and 
Arduino 1.8.16 after press reset on ESP board:
```
20:24:35.642 -> 9Zv⸮c/a{)a5⸮⸮⸮V:⸮aQVHhello #0
20:24:37.143 -> hello #1
20:24:37.658 -> hello #2
20:24:38.128 -> hello #3
20:24:38.641 -> hello #4
20:24:39.153 -> hello #5
20:24:39.622 -> hello #6
20:24:40.136 -> hello #7
20:24:40.648 -> hello #8
20:24:41.159 -> hello #9
20:24:41.625 -> hello #10
20:24:42.138 -> hello #11
```
and led blinks

### Expected behavior

to have the same output as on Arduino 1.8.16

### serial-monitor version

arduino-cli.exe  Version: nightly-20220519 Commit: 6883b39 Date: 2022-05-19T01:34:16Z

### Operating system

Windows

### Operating system version

10 Pro 21H2

### Additional context

please implement the behavior on Arduino 2.0 as on Arduino 1.8.16

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/serial-monitor/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by cmaglie** [comment] 2022-05-24 09:48
Hi @Erhie !

I've read the discussion on the forum, it's a really bad issue.

I'd like to send you a small terminal program written in golang to try out, to further reduce the possible causes. May you compile a golang program in case?
Otherwise I can post here a prebuild executable if you're ok with that.

**Comment by cmaglie** [comment] 2022-05-24 10:06
```go
package main

import (
	"fmt"
	"os"
	"strconv"

	"go.bug.st/serial"
)

func usage() {
	fmt.Println("Usage: term <PORT> [baudrate]")
	os.Exit(1)
}

func main() {
	args := os.Args[1:]
	if len(args) == 0 {
		usage()
	}
	portname, args := args[0], args[1:]
	baudrate := 9600
	if len(args) > 0 {
		if b, err := strconv.Atoi(args[0]); err != nil {
			fmt.Println("Invalid baudrate:", args[0])
			os.Exit(1)
		} else {
			baudrate = b
		}
		args = args[1:]
	}
	if len(args) > 0 {
		usage()
	}

	port, err := serial.Open(portname, &serial.Mode{BaudRate: baudrate})
	if err != nil {
		fmt.Printf("Error opening serial port %s: %s\n", portname, err)
		os.Exit(2)
	}

	var buff [1024]byte
	for {
		n, err := port.Read(buff[:])
		if err != nil {
			fmt.Println("Error reading from serial port:", err)
			break
		}
		if n == 0 {
			fmt.Println("Timeout reading from serial port.")
			continue
		}
		os.Stdout.Write(buff[:n])
	}

	port.Close()
}
```

ok this is the program, it should be run like this:

```
C:\> go run main.go COM1
Connected to COM1
16814
16815
16816
16817
16818
16819
16820
16821  <--- this is the output from my board
16822
16823
16824
16825
16826
16827
```

Otherwise you can use this precompiled [term.exe](https://github.com/arduino/serial-monitor/files/8761638/term.zip), you should run it the same:

```
C:\> term.exe COM1
Connected to COM1
16814
16815
16816
16817
16818
16819
16820
...
```

**Comment by cmaglie** [comment] 2022-05-31 14:27
I've been looking at the Arduino IDE 1.8.x source code and I see that the IDE is explicitly setting RTS/CTS:

https://github.com/arduino/Arduino/blob/43b0818f7fa8073301db1b80ac832b7b7596b828/arduino-core/src/processing/app/Serial.java#L81-L87

On the IDE 1.8 they are always enabled (unless specified otherwise), instead on the IDE 2.0/CLI they are left "untouched". It may be that the board you're using requires an explicit activation of those bits, something to try out.

**Comment by ubidefeo** [comment] 2022-08-05 15:05
@Erhie
have you had any chance to follow up on testing?

**Comment by Erhie** [comment] 2022-08-06 11:56
> at last I use Arduino IDE 1.8.19 and forgot IDE 2.0

**Comment by Erhie** [comment] 2022-08-08 09:51
now I test IDE 2.0 rc9.1
with the script below, but have no output in serial monitor
with IDE 1.8.19 it works fine

int i = 0;
void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  // Serial.setDebugOutput(true); uncommented by OpaErhard
  Serial.println();
}

void loop() {
  // put your main code here, to run repeatedly:
  Serial.println(i++);
}

**Comment by per1234** [comment] 2022-08-08 10:14
Thanks @Erhie. Are you able to run the test that was requested above at this comment?

https://github.com/arduino/serial-monitor/issues/17#issuecomment-1135705291

Please let us know if you have any questions or problems.

**Comment by Erhie** [comment] 2022-08-09 21:09
sorry, I have problems with Go

with VS code 
Build Error: go build -o h:\Users\gle\Documents\Arduino\__debug_bin.exe -gcflags all=-N -l .
package example.com/m: C source files not allowed when not using cgo or SWIG: led.c

don't know how to fix it because all helps are for Linux alike

**Comment by per1234** [comment] 2022-08-10 02:59
It seems you have a file named `led.c` in the same folder as the Go program. You must remove any unnecessary files from the folder.

I'll provide complete instructions (omitting installation of Go since I can see you already have it):

1. Start the Arduino IDE.
1. Connect your **ESP32-CAM-MB** board to your computer as usual.
1. Select **Tools > Port** from the Arduino IDE menus.
1. Note which serial port your **ESP32-CAM-MB** board is on.
1. Select **File > Quit** from the Arduino IDE menus.
1. Hover the mouse pointer over the box below. You will see an icon appear at the top right corner. Click that icon to copy the code to the clipboard.
   ```go
   package main
   
   import (
   	"fmt"
   	"os"
   	"strconv"
   
   	"go.bug.st/serial"
   )
   
   func usage() {
   	fmt.Println("Usage: term <PORT> [baudrate]")
   	os.Exit(1)
   }
   
   func main() {
   	args := os.Args[1:]
   	if len(args) == 0 {
   		usage()
   	}
   	portname, args := args[0], args[1:]
   	baudrate := 9600
   	if len(args) > 0 {
   		if b, err := strconv.Atoi(args[0]); err != nil {
   			fmt.Println("Invalid baudrate:", args[0])
   			os.Exit(1)
   		} else {
   			baudrate = b
   		}
   		args = args[1:]
   	}
   	if len(args) > 0 {
   		usage()
   	}
   
   	port, err := serial.Open(portname, &serial.Mode{BaudRate: baudrate})
   	if err != nil {
   		fmt.Printf("Error opening serial port %s: %s\n", portname, err)
   		os.Exit(2)
   	}
   
   	var buff [1024]byte
   	for {
   		n, err := port.Read(buff[:])
   		if err != nil {
   			fmt.Println("Error reading from serial port:", err)
   			break
   		}
   		if n == 0 {
   			fmt.Println("Timeout reading from serial port.")
   			continue
   		}
   		os.Stdout.Write(buff[:n])
   	}
   
   	port.Close()
   }
   ```
1. Create a new folder.
   **ⓘ** The folder can be at any convenient location and with any name you like.
1. Create a file in the folder with the name `main.go`
1. [Paste](https://lifehacker.com/how-to-copy-cut-and-paste-for-beginners-5801525) the code you copied at step (6) into the file `main.go`
1. Open a terminal at the folder path.
   **ⓘ** You can use any terminal you prefer (e.g., PowerShell, Command Prompt, cmd, Bash)
1. Run the following command from the terminal  to initialize the Go project:
   ```text
   go mod init example.com/foo
   ```
1. Run the following command from the terminal to install the dependencies of the project:
   ```text
   go get
   ```
1. Run the following command from the terminal to run the Go program:
   ```text
   go run main.go <port>
   ```
   ❗ Replace `<port>` in the command with the serial port of your **ESP32-CAM-MB** board, as determined at step (4) of the instructions.

Please let me know if you have any questions or problems while following those instructions.

---

If you prefer, you can also try the executable provided by @cmaglie in the previous reply:

>Otherwise you can use this precompiled [term.exe](https://github.com/arduino/serial-monitor/files/8761638/term.zip), you should run it the same:

Unfortunately, Windows Defender was not happy about the file when I downloaded it to my computer, so it is possible you will have difficulty with that approach as well, but maybe worth a try if building the program from source is not convenient?

**Comment by Erhie** [comment] 2022-08-10 11:55
Thank you for your patience with me.
Sorry,
with **Select File > Quit** from the Arduino IDE menus
**Arduino IDE exits** and no possibility to over the mouse pointer over the box below

**Comment by per1234** [comment] 2022-08-10 12:10
>Thank you for your patience with me.

You are welcome.

Thanks to you for assisting us with this investigation.

>no possibility to over the mouse pointer over the box below

The box is in my previous reply here on GitHub:

![image](https://user-images.githubusercontent.com/8572152/183897420-856bd2c8-241b-4b94-88ca-3fc8e3972fb6.png)

**Comment by cmaglie** [comment] 2022-08-10 17:44
Hi @Erhie,

maybe it's more simple if you get the zip here -> [term.zip](https://github.com/arduino/serial-monitor/files/9302682/term.zip)
It contains a `term` folder with the go test code already written, you just need to open a command propmt and execute

`go run main.go COM5`

from the `term' folder.

**Comment by Erhie** [comment] 2022-08-11 10:39
sorry, more packages are need:

PS H:\Users\gle\Documents\ArduinoGo2\term> go run main.go COM5
C:\Users\gle\go\pkg\mod\golang.org\x\sys@v0.0.0-20210823070655-63515b42dcdf\windows\syscall.go:28:2: package bytes is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\bytes)
C:\Users\gle\go\pkg\mod\golang.org\x\sys@v0.0.0-20210823070655-63515b42dcdf\windows\exec_windows.go:10:2: package errors is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\errors)
main.go:4:2: package fmt is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\fmt)
C:\Users\gle\go\pkg\mod\golang.org\x\sys@v0.0.0-20210823070655-63515b42dcdf\windows\types_windows.go:8:2: package net is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\net)
main.go:5:2: package os is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\os)
C:\Users\gle\go\pkg\mod\golang.org\x\sys@v0.0.0-20210823070655-63515b42dcdf\windows\syscall_windows.go:12:2: package runtime is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\runtime)
main.go:6:2: package strconv is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\strconv)
C:\Users\gle\go\pkg\mod\golang.org\x\sys@v0.0.0-20210823070655-63515b42dcdf\windows\syscall.go:29:2: package strings is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\strings)
C:\Users\gle\go\pkg\mod\golang.org\x\sys@v0.0.0-20210823070655-63515b42dcdf\windows\dll_windows.go:8:2: package sync is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\sync)
C:\Users\gle\go\pkg\mod\golang.org\x\sys@v0.0.0-20210823070655-63515b42dcdf\windows\dll_windows.go:9:2: package sync/atomic is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\sync\atomic)
C:\Users\gle\go\pkg\mod\golang.org\x\sys@v0.0.0-20210823070655-63515b42dcdf\windows\aliases.go:10:8: package syscall is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\syscall)
C:\Users\gle\go\pkg\mod\golang.org\x\sys@v0.0.0-20210823070655-63515b42dcdf\windows\syscall_windows.go:15:2: package time is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\time)
C:\Users\gle\go\pkg\mod\golang.org\x\sys@v0.0.0-20210823070655-63515b42dcdf\windows\syscall_windows.go:16:2: package unicode/utf16 is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\unicode\utf16)
C:\Users\gle\go\pkg\mod\golang.org\x\sys@v0.0.0-20210823070655-63515b42dcdf\internal\unsafeheader\unsafeheader.go:14:2: package unsafe is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\unsafe)

**Comment by cmaglie** [comment] 2022-08-11 12:18
```
package unicode/utf16 is not in GOROOT (C:\Users\gle\scoop\apps\go\current\src\unicode\utf16)
```

The package `unicode/utf16` should is part of the golang system libraries (same for all the other missing packages).
Are you sure that your installation of go is good?

**Comment by Erhie** [comment] 2022-08-11 13:41
I just managed it.
I had many Go installations, so I uninstalled all
and purged all set variables for them and the path entries for them.
I installed Go for Windows with go1.19.windows-amd64.msi
And add a new path entry to C:\Program Files\Go\bin .
Started powershell again that the prompt shows our path H:\Users\gle\Documents\ArduinoGo2\term

go build reports 
go: downloading go.bug.st/serial v1.3.5
go: downloading golang.org/x/sys v0.0.0-20210823070655-63515b42dcdf

On my ESP32-cam board I loaded the sketch
int i = 0;
void setup() {
  Serial.begin(9600);
}
void loop() {
  Serial.println(i++);
  delay(1000);
}
and the serial monitor of IDE 1.8.19 shows the expected output.
After  quitting the IDE 
In Powershell again
go run main.go COM5
it runs, but see no output

**Comment by cmaglie** [comment] 2022-08-11 14:03
ok could you try this variant:
```go
package main

import (
	"fmt"
	"os"
	"strconv"

	"go.bug.st/serial"
)

func usage() {
	fmt.Println("Usage: term <PORT> [baudrate]")
	os.Exit(1)
}

func main() {
	args := os.Args[1:]
	if len(args) == 0 {
		usage()
	}
	portname, args := args[0], args[1:]
	baudrate := 9600
	if len(args) > 0 {
		if b, err := strconv.Atoi(args[0]); err != nil {
			fmt.Println("Invalid baudrate:", args[0])
			os.Exit(1)
		} else {
			baudrate = b
		}
		args = args[1:]
	}
	if len(args) > 0 {
		usage()
	}

	port, err := serial.Open(portname, &serial.Mode{BaudRate: baudrate})
	if err != nil {
		fmt.Printf("Error opening serial port %s: %s\n", portname, err)
		os.Exit(2)
	}

	port.SetDTR(true)  // <-----------------
	port.SetRTS(true)  // <-----------------

	var buff [1024]byte
	for {
		n, err := port.Read(buff[:])
		if err != nil {
			fmt.Println("Error reading from serial port:", err)
			break
		}
		if n == 0 {
			fmt.Println("Timeout reading from serial port.")
			continue
		}
		os.Stdout.Write(buff[:n])
	}

	port.Close()
}
```

I've added the two lines marked with the arrows:

```go
	port.SetDTR(true)  // <-----------------
	port.SetRTS(true)  // <-----------------
```

that sets the DTR and RTS bits of the port. It's the only difference I found with the Arduino IDE 1.8.x.
I'd like to ask you to try all the four different combinations:

|  DTR  |  RTS  |  Result |
|------|-----|------------|
| true | true |   .....    |
| true | false |
| false | true |
| false | false |

I hope that this unlocks something, otherwise, I'm out of ideas...

**Comment by Erhie** [comment] 2022-08-11 18:35
it seems that **false, false** is promising.
	/*
	port.SetDTR(true)  // <-----------------
	port.SetRTS(true)  // <-----------------
	nothing to see */

	/* 
	port.SetDTR(false)  // <-----------------
	port.SetRTS(false)  // <-----------------
	restarts esp32 and this in output
Q�6�\:�q�}��c Q%�0
1
2
3
4
	*/

	/*
	port.SetDTR(true)  // <-----------------
	port.SetRTS(false)  // <-----------------
	this in output
�0�.�Z�Z
	*/

	port.SetDTR(false)  // <-----------------
	port.SetRTS(true)  // <-----------------
	/* nothing to see */

**Comment by cmaglie** [comment] 2022-09-21 13:27
@Erhie 
we just published an update to the `serial-monitor` to account for RTS/DTR signals.
Could you retry with the latest Arduino IDE 2.0.0? it should now automatically download and update the `serial-monitor` tool.

**Comment by umbynos** [comment] 2022-10-17 14:04
Hey @Erhie do you find the time to check it out? :smile:

**Comment by cmaglie** [comment] 2022-12-01 10:24
I'm closing this as fixed.

@Erhie if the issue is not fixed for you feel free to re-open.

**Closed by cmaglie** 2022-12-01 10:24 UTC
Labels: type: imperfection, status: waiting for information
